name: humic_payroll_mobile_app
version: 1.0.0+1
publish_to: none
description: A HUMiC Payroll Mobile Application.
environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  excel: ^4.0.6
  file_picker: ^8.1.4
  fl_chart: ^0.69.0
  fluentui_system_icons: ^1.1.259
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  get: ^4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  iconify_flutter: ^0.0.7
  image_picker: ^1.1.2
  intl: ^0.18.1
  lottie: ^3.1.2
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  random_color: ^1.0.6-nullsafety
  rename: ^3.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/humic-engineering.png"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
